from datetime import datetime


class Gender:
    F = ...
    M = ...

class Region:
    Alba = ...
    Arad = ...
    Arges = ...
    Bacau = ...
    Bihor = ...
    Bistrita_Nasaud = ...
    Botosani = ...
    Brasov = ...
    Braila = ...
    Buzau = ...
    Caras_Severin = ...
    Cluj = ...
    Constanta = ...
    Covasna = ...
    Dambovita = ...
    Dolj = ...
    Galati = ...
    Gorj = ...
    Hargita = ...
    Hunedoara = ...
    Ialomita = ...
    Iasi = ...
    Ilfov = ...
    Maramures = ...
    Mehedinti = ...
    Mures = ...
    Neamt = ...
    Olt = ...
    Prahova = ...
    Satu_Mare = ...
    Salaj = ...
    Sibiu = ...
    Suceava = ...
    Teleorman = ...
    Timis = ...
    Tulcea = ...
    Vaslui = ...
    Valcea = ...
    Vrancea = ...
    Bucuresti = ...
    Bucuresti_Sector__1 = ...
    Bucuresti_Sector__2 = ...
    Bucuresti_Sector__3 = ...
    Bucuresti_Sector__4 = ...
    Bucuresti_Sector__5 = ...
    Bucuresti_Sector__6 = ...
    Calarasi = ...
    Giurgiu = ...

class Cnp:

    REF_CONSTANT: list = ...
    LENGTH: int = ...
    PARTIAL_LENGTH: int = ...

    def __init__(self, gender: Gender, birth_date: datetime, region: Region, serial: int = 1,  resident: bool = False) -> Cnp:
        self.gender: Gender = ...
        self.birth_date: datetime = ...
        self.region: Region = ...
        self.serial: int = ...
        self.resident: bool = ...
    def get_gender_code(self) -> int: ...
    @property
    def partial(self) -> str: ...
    @property
    def full(self) -> str: ...
    @staticmethod
    def compute_c(partial: str) -> int: ...
    @staticmethod
    def is_valid(_cnp: str) -> bool: ...
